# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_auto_20170730_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.CommentModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.UserModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='post',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
